import React from 'react';
import { BarChart3, Plane, TrendingUp, Lightbulb } from 'lucide-react';

const WelcomePlaceholder = () => {
  return (
    <div className="flex items-center justify-center h-full p-4">
      <div className="text-center bg-white p-8 md:p-12 rounded-xl shadow-lg border border-gray-200 w-full max-w-4xl">
        <BarChart3 className="mx-auto h-12 w-12 text-brand-primary" />
        <h2 className="mt-4 text-2xl font-bold text-brand-dark">
          Welcome to the Airline Demand Analyzer
        </h2>
        <p className="mt-2 text-sm text-gray-600">
          Get started by entering an origin, destination, and date range above.
        </p>

        <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-8 text-left">
          {/* Feature 1 */}
          <div className="flex items-start">
            <div className="flex-shrink-0">
              <Plane className="h-6 w-6 text-brand-secondary" />
            </div>
            <div className="ml-4">
              <h3 className="text-sm font-semibold text-brand-dark">Find Flight Offers</h3>
              <p className="mt-1 text-xs text-gray-500">
                Instantly search for flight options across a wide range of dates.
              </p>
            </div>
          </div>
          {/* Feature 2 */}
          <div className="flex items-start">
            <div className="flex-shrink-0">
              <TrendingUp className="h-6 w-6 text-brand-secondary" />
            </div>
            <div className="ml-4">
              <h3 className="text-sm font-semibold text-brand-dark">Visualize Price Trends</h3>
              <p className="mt-1 text-xs text-gray-500">
                Analyze daily price variations with an interactive chart.
              </p>
            </div>
          </div>
          {/* Feature 3 */}
          <div className="flex items-start">
            <div className="flex-shrink-0">
              <Lightbulb className="h-6 w-6 text-brand-secondary" />
            </div>
            <div className="ml-4">
              <h3 className="text-sm font-semibold text-brand-dark">Get AI-Powered Insights</h3>
              <p className="mt-1 text-xs text-gray-500">
                Receive an actionable market summary generated by AI.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default WelcomePlaceholder;
